research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Based on the industry conducted, analyze industry trends and standards within the 
    {topic}’s sector related to AI, ML, and automation.
    Propose relevant use cases where the company can leverage GenAI, LLMs, and ML technologies to improve their processes, 
    enhance customer satisfaction, and boost operational efficiency.
  expected_output: >
    Collect the above use cases generated and search for relevant datasets on platforms like Kaggle, HuggingFace, and GitHub.
    Save the resource links fetched in a text or markdown file.
    Formatted as markdown without '```'
  agent: reporting_analyst
